### ISSUE TITLE
Deployment shell script has problems

### ISSUE THREAD

**Issue by snowsignal** [workforce-data-initiative/etp-api#11]
Whenever you run the ```./deploy.sh``` script, it updates the app you have published on Heroku, but also creates a new blank app in your account, and adds a new blank Postgres database to the main app. Are other people encountering the same behavior?

**Comment by NdagiStanley** [comment]
I'll take a look @JacksonCoder.

**Comment by snowsignal** [comment]
Upon closer inspection, it seems that the deploy script seems to be more of an initialization script. I think that it would be best if we created two separate shell scripts, one for initially creating an app, then one for updating it.

**Comment by gitgik** [comment]
Thank you @JacksonCoder for fixing this. 🔥
